CREATE TABLE IF NOT EXISTS users
(
    id       LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE NOT NULL,
    login    VARCHAR(255)        NOT NULL,
    name     VARCHAR(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS films
(
    id           LONG GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date date,
    duration     INTEGER
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id LONG REFERENCES films (id) ON DELETE CASCADE,
    user_id LONG REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    id_from LONG REFERENCES users (id) ON DELETE CASCADE,
    id_to   LONG REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (id_from, id_to)
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id   LONG REFERENCES films (id) ON DELETE CASCADE,
    genres_id LONG DEFAULT 0,
    UNIQUE (film_id, genres_id)
);

CREATE TABLE IF NOT EXISTS films_mpa
(
    film_id LONG REFERENCES films (id) ON DELETE CASCADE,
    mpa_id  LONG DEFAULT 0,
    UNIQUE (film_id, mpa_id)
);